# Generated by Django 5.1.3 on 2024-11-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ideas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Processstep',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ('title',),
            },
        ),
    ]
