# Generated by Django 5.1.3 on 2024-11-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mission_statement', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'CompanyInfo',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Teammember',
                'ordering': ('name',),
            },
        ),
    ]
